
import React from 'react';
import { Button } from '@/components/ui/button';
import { ArrowRight, Upload, Camera } from 'lucide-react';

const HeroSection: React.FC = () => {
  return (
    <section className="py-20 relative overflow-hidden">
      <div className="container mx-auto px-4">
        <div className="flex flex-col lg:flex-row items-center justify-between gap-12">
          <div className="lg:w-1/2">
            <h1 className="text-4xl md:text-5xl font-bold leading-tight mb-6">
              <span className="text-gradient-primary">Authenticate</span> Images with
              <span className="block mt-2">3D AI Vision</span>
            </h1>
            
            <p className="text-muted-foreground text-lg mb-8 max-w-xl">
              Our cutting-edge AI technology detects and verifies the authenticity of images, 
              helping you identify AI-generated content with precision and confidence.
            </p>
            
            <div className="flex flex-wrap gap-4">
              <Button className="bg-neon-purple hover:bg-neon-purple/80 transition-colors gap-2">
                <Upload size={18} />
                Upload Image
              </Button>
              
              <Button variant="outline" className="border-neon-blue text-neon-blue hover:bg-neon-blue/10 gap-2">
                <Camera size={18} />
                Live Camera
              </Button>
              
              <Button variant="link" className="text-neon-pink gap-1 pl-1">
                Learn More <ArrowRight size={16} />
              </Button>
            </div>
          </div>
          
          <div className="lg:w-1/2 relative">
            <div className="h-[400px] w-full max-w-[500px] mx-auto relative glass-morphism rounded-xl overflow-hidden animate-float">
              <div className="absolute inset-0 flex items-center justify-center flex-col text-center p-8 bg-gradient-to-b from-transparent to-background/90">
                <div className="w-16 h-16 rounded-full bg-neon-purple/20 flex items-center justify-center mb-4">
                  <Camera className="text-neon-purple" size={28} />
                </div>
                <h3 className="text-xl font-semibold mb-2">Drop Your Image Here</h3>
                <p className="text-muted-foreground text-sm max-w-xs">
                  Our AI will analyze and determine if it's generated by artificial intelligence
                </p>
              </div>
            </div>
            
            {/* Floating elements decoration */}
            <div className="absolute top-10 right-10 w-6 h-6 rounded-full bg-neon-blue opacity-70 animate-pulse-glow"></div>
            <div className="absolute bottom-16 left-10 w-4 h-4 rounded-full bg-neon-pink opacity-70 animate-pulse-glow animation-delay-300"></div>
            <div className="absolute top-1/2 left-1/4 w-8 h-8 rounded-full border border-neon-purple opacity-60 animate-spin-slow"></div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
