// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flmdplalgazpcsycznls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbWRwbGFsZ2F6cGNzeWN6bmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjM0OTAsImV4cCI6MjA1OTc5OTQ5MH0.XrwXSVF5Y3TXX37Vqcj4-mOJVlo1nu7GnXhmvmMGiLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);